name: 'release'
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git Identity
        run: |
          git config --global user.name 'Iron Robot'
          git config --global user.email 'team@ironplans.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn install --frozen-lockfile
      - run: make $(lerna changed -p | xargs -n1 basename)
      - run: lerna publish --yes --no-verify-access
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
