name: 'checks'
on:
  pull_request:
    branches:
      - main

jobs:
  size:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['openapi/api']
    steps:
      - uses: actions/checkout@v2
      - uses: andresz1/size-limit-action@v1
        with:
          directory: packages/${{ matrix.package }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
